[build]
builder = "nixpacks"

[deploy]
numReplicas = 1

[[services]]
name = "frontend"
root = "."
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"

[[services]]
name = "backend"
root = "./backend"
startCommand = "python app.py"

[[services]]
name = "postgres"
image = "postgres:15"
volumes = ["/var/lib/postgresql/data"]

[services.postgres.variables]
POSTGRES_DB = "figma_catalog"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "${{ secret.POSTGRES_PASSWORD }}"