[build]
builder = "nixpacks"

[deploy]
numReplicas = 1

[[services]]
name = "frontend"
root = "./frontend"
buildCommand = "npm install && npm run build"
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"

[[services]]
name = "backend"
root = "./backend"
buildCommand = "pip install -r requirements.txt"
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[[services]]
name = "postgres"
image = "postgres:15"
volumes = ["/var/lib/postgresql/data"]

[services.postgres.variables]
POSTGRES_DB = "figma_catalog"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "${{ secret.POSTGRES_PASSWORD }}"
