name = "figma-product-catalog-api"
main = "worker_fixed.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-04-01"

[vars]
PROJECT_NAME = "Figma Product Catalog"
API_VERSION = "1.0.0"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "figma-catalog-db"
database_id = "49caef12-1fad-4424-b78c-019d269e0d69"

# Optional: Add KV namespace for caching
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"