name = "crm-bitrix"
main = "src/worker.js"
compatibility_date = "2024-10-01"
type = "javascript"

# Assets binding for SPA
[assets]
directory = "dist"
binding = "ASSETS"

[env.production]
name = "crm-bitrix-production"
routes = [
  { pattern = "crm-bitrix.workers.dev/*" }
]
